package entities;
// Generated 01/08/2015 18:08:32 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TarefaExecucao generated by hbm2java
 */
@Entity
@Table(name="tarefa_execucao"
    ,schema="public"
)
public class TarefaExecucao  implements java.io.Serializable {


     private int id;
     private Tarefa tarefa;
     private String status;
     private Date created;

    public TarefaExecucao() {
    }

	
    public TarefaExecucao(int id, Tarefa tarefa, String status) {
        this.id = id;
        this.tarefa = tarefa;
        this.status = status;
    }
    public TarefaExecucao(int id, Tarefa tarefa, String status, Date created) {
       this.id = id;
       this.tarefa = tarefa;
       this.status = status;
       this.created = created;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tarefa_id", nullable=false)
    public Tarefa getTarefa() {
        return this.tarefa;
    }
    
    public void setTarefa(Tarefa tarefa) {
        this.tarefa = tarefa;
    }

    
    @Column(name="status", nullable=false, length=20)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", length=29)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }




}


