/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tarefateste;

import entities.Usuario;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import model.TarefaModel;
import model.UsuarioModel;

/**
 *
 * @author timi
 */
public class JFramePrincipal extends javax.swing.JFrame {

    public final static String TITULO = "Sistema de tarefas - ";
    public Usuario usuarioLogado;
    public UsuarioModel usuarioModel = new UsuarioModel();
    private JInternalFrameTarefa frameTarefa;
    private JInternalFrameUsuario frameUsuario;
    private JInternalFrameTarefaExecucao frameExecucao;

    /**
     * Creates new form JFrameUsuario
     */
    public JFramePrincipal() {
        try {
//            TarefaModel tf = new TarefaModel();
//    
//            
//            tf.getMinhasTarefas();
            initComponents();
            //login
            JDialogLogin dlg = new JDialogLogin(this, true);
//            UsuarioModel um = new UsuarioModel();
//            usuarioLogado = um.find(1);
            
            if (!(usuarioLogado instanceof Usuario)) {
                System.exit(0);
            }
            
            TrayIconApp trayIcon = new TrayIconApp();
            trayIcon.createAndShowGUI(this);

            frameExecucao = new JInternalFrameTarefaExecucao(this);
            this.desktop.add(frameExecucao);
            frameExecucao.setMaximum(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArquivo = new javax.swing.JMenu();
        jMenuLogout = new javax.swing.JMenuItem();
        jMenuFechar = new javax.swing.JMenuItem();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemTarefa = new javax.swing.JMenuItem();
        jMenuItemUsuario = new javax.swing.JMenuItem();
        jMenuMinhasTarefas = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Tarefas");
        setIconImage(TrayIconApp.createImage("/resources/images/icon.png", ""));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setPreferredSize(new java.awt.Dimension(700, 500));
        setResizable(false);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 687, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );

        jMenuArquivo.setText("Arquivo");
        jMenuArquivo.setMargin(new java.awt.Insets(2, 2, 2, 10));

        jMenuLogout.setText("Trocar Usuário");
        jMenuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLogoutActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuLogout);

        jMenuFechar.setText("Sair");
        jMenuFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFecharActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuFechar);

        jMenuBar1.add(jMenuArquivo);

        jMenuCadastro.setText("Cadastro");
        jMenuCadastro.setMargin(new java.awt.Insets(2, 2, 2, 10));

        jMenuItemTarefa.setText("Tarefas");
        jMenuItemTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTarefaActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemTarefa);

        jMenuItemUsuario.setText("Usuários");
        jMenuItemUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuarioActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemUsuario);

        jMenuBar1.add(jMenuCadastro);

        jMenuMinhasTarefas.setText("Minhas tarefas");
        jMenuMinhasTarefas.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenuMinhasTarefasMenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenuMinhasTarefas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktop)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktop)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(715, 522));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void ocultaTudo() {
        if (frameTarefa instanceof JInternalFrame) {
            frameTarefa.setVisible(false);
        }
        if (getFrameExecucao() instanceof JInternalFrame) {
            getFrameExecucao().setVisible(false);
        }
        if (frameUsuario instanceof JInternalFrame) {
            frameUsuario.setVisible(false);
        }
    }


    private void jMenuItemTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTarefaActionPerformed
        exibeCadastroTarefa();
    }//GEN-LAST:event_jMenuItemTarefaActionPerformed

    public void exibeCadastroTarefa() {
        try {
            ocultaTudo();
            if (!(frameTarefa instanceof JInternalFrameTarefa)) {
                frameTarefa = new JInternalFrameTarefa(this);
                desktop.add(frameTarefa);
            } else {
                frameTarefa.atualiza();
            }
            frameTarefa.setVisible(true);
            frameTarefa.setMaximum(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private void jMenuItemUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuarioActionPerformed
        exibeCadastroUsuario();
    }//GEN-LAST:event_jMenuItemUsuarioActionPerformed

    public void exibeCadastroUsuario() {
        try {
            ocultaTudo();
            if (!(frameUsuario instanceof JInternalFrameUsuario)) {
                frameUsuario = new JInternalFrameUsuario(this);
                desktop.add(frameUsuario);
            } else {
                frameUsuario.preencheTabela();
            }
            frameUsuario.setVisible(true);
            frameUsuario.setMaximum(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private void jMenuMinhasTarefasMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenuMinhasTarefasMenuSelected
        exibeMinhasTarefas();
    }//GEN-LAST:event_jMenuMinhasTarefasMenuSelected

    public void exibeMinhasTarefas() {
        try {
            ocultaTudo();
            if (!(frameExecucao instanceof JInternalFrameTarefaExecucao)) {
                setFrameExecucao(new JInternalFrameTarefaExecucao(this));
                desktop.add(getFrameExecucao());
            } else {
                getFrameExecucao().atualiza();
            }
            getFrameExecucao().setVisible(true);
            getFrameExecucao().setMaximum(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private void jMenuFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFecharActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuFecharActionPerformed

    private void jMenuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLogoutActionPerformed
        trocarUsuario();
    }

    public void trocarUsuario() {
        try {
            int idPre = this.usuarioLogado.getId();
            JDialogLogin jdl = new JDialogLogin(this, true);
            if (!(usuarioLogado instanceof Usuario)) {
                System.exit(0);
            }
            if (this.usuarioLogado.getId() != idPre) {
                this.desktop.removeAll();
                this.frameTarefa = null;
                this.frameUsuario = null;
                this.frameExecucao = new JInternalFrameTarefaExecucao(this);
                this.desktop.add(frameExecucao);
                this.frameExecucao.setMaximum(true);
            }
            this.setVisible(true);
            this.setExtendedState(JFrame.NORMAL);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jMenuLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePrincipal().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenu jMenuArquivo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenuItem jMenuFechar;
    private javax.swing.JMenuItem jMenuItemTarefa;
    private javax.swing.JMenuItem jMenuItemUsuario;
    private javax.swing.JMenuItem jMenuLogout;
    private javax.swing.JMenu jMenuMinhasTarefas;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the frameExecucao
     */
    public JInternalFrameTarefaExecucao getFrameExecucao() {
        return frameExecucao;
    }

    /**
     * @param frameExecucao the frameExecucao to set
     */
    public void setFrameExecucao(JInternalFrameTarefaExecucao frameExecucao) {
        this.frameExecucao = frameExecucao;
    }
}
