/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tarefateste;


import entities.Tarefa;
import entities.Usuario;
import java.text.SimpleDateFormat;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import model.TarefaModel;
import model.UsuarioModel;
import util.CustomCombo;
import util.DocumentMaxLength;

/**
 *
 * @author timi
 */
public class JInternalFrameTarefa extends javax.swing.JInternalFrame {

    private TarefaModel tarefaModel = new TarefaModel();
    private JFramePrincipal framePrincipal;
    private Tarefa tarefaUpdate = null;

    /**
     * Creates new form JInternalFrameTarefa
     * @param framePrincipal
     */
    public JInternalFrameTarefa(JFramePrincipal framePrincipal) {
        try { 
            initComponents();
            BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
            bi.setNorthPane(null);
            this.framePrincipal = framePrincipal;
            this.jTextFieldTitulo.setDocument(new DocumentMaxLength(100));
            preencheTabela();
            preencheCombos();
            this.jButtonCancelar.setVisible(false);
            this.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }

    private void preencheTabela() {

        DefaultTableModel dtm = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        dtm.addColumn("#");
        dtm.addColumn("Título");
        dtm.addColumn("Criada por");
        dtm.addColumn("Responsável");
        dtm.addColumn("Esforco estimado");
        dtm.addColumn("Status");
        dtm.addColumn("Data criação");
        for (Tarefa tarefa : this.tarefaModel.findAll()) {
            dtm.addRow(new Object[]{tarefa.getId(),
                tarefa.getTitulo(),
                tarefa.getUsuarioByIdUsuarioCriador().getNome(),
                tarefa.getUsuarioByIdUsuarioExecutor().getNome(),
                ((tarefa.getEsforcoEstimado() > 1) ? (tarefa.getEsforcoEstimado() + " horas") : (tarefa.getEsforcoEstimado() + " hora")),
                tarefa.getStatus(),
                 new SimpleDateFormat("dd/MM/yyyy").format(tarefa.getCreated()),
            });
        }
        this.jTableTarefa.setModel(dtm);
        this.jTableTarefa.getColumnModel().getColumn(0).setPreferredWidth(10);
        
    }

    public void atualiza() {
        preencheTabela();
        preencheCombos();
    }
    private void resetCadastro() {
        this.tarefaUpdate = null;
        this.jComboBoxUsuario.setEnabled(true);
        this.jButtonCancelar.setVisible(false);
        this.jTextFieldTitulo.setText("");
        this.jComboBoxUsuario.setSelectedIndex(0);
        this.jComboBoxEsforco.setSelectedIndex(0);
        this.jTextAreaDescricao.setText("");
        this.jPanel1.setBorder(BorderFactory.createTitledBorder("Cadastrar nova tarefa"));
    }
    private void preencheCombos() {
        UsuarioModel usuarioModel = new UsuarioModel();
        DefaultComboBoxModel dcbm = new DefaultComboBoxModel();
        dcbm.addElement(new CustomCombo(0, "Selecione"));
        for (Usuario u : usuarioModel.findAll()) {
            dcbm.addElement(new CustomCombo(u.getId(), u.getNome()));
        }
        this.jComboBoxUsuario.removeAllItems();
        this.jComboBoxUsuario.setModel(dcbm);

        DefaultComboBoxModel dcbm2 = new DefaultComboBoxModel();
        dcbm2.addElement(new CustomCombo(0, "Selecione"));
        for (int i = 1; i <= 48; i++) {
            dcbm2.addElement(new CustomCombo(i, ((i > 1) ? (i + " horas") : (i + " hora"))));
        }
        this.jComboBoxEsforco.removeAllItems();
        this.jComboBoxEsforco.setModel(dcbm2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTarefa = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldTitulo = new javax.swing.JTextField();
        jButtonCadastrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxUsuario = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxEsforco = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaDescricao = new javax.swing.JTextArea();
        jButtonCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel5.setText("Descrição");

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Cadastro de tarefas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        setTitle("Cadastro de tarefa");
        setMinimumSize(new java.awt.Dimension(655, 425));
        setNextFocusableComponent(jTableTarefa);
        setNormalBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setPreferredSize(new java.awt.Dimension(655, 425));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);

        jTableTarefa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableTarefa.setName(""); // NOI18N
        jTableTarefa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTarefaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableTarefa);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastrar nova tarefa"));

        jLabel1.setText("Título");

        jButtonCadastrar.setText("Salvar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        jLabel3.setText("Responsável");

        jComboBoxUsuario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Esforço");

        jComboBoxEsforco.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Descrição");

        jTextAreaDescricao.setColumns(20);
        jTextAreaDescricao.setRows(5);
        jScrollPane3.setViewportView(jTextAreaDescricao);

        jButtonCancelar.setText("Cancelar Edição");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addComponent(jLabel1))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel3))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxEsforco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonCadastrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonCancelar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxEsforco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastrar)
                    .addComponent(jButtonCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("*Duplo clique na lista para editar a tarefa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 429, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableTarefaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTarefaMouseClicked
        try {
            if (evt.getClickCount() == 2) {
                int indice = this.jTableTarefa.getSelectedRow();
                String id = this.jTableTarefa.getValueAt(indice, 0).toString();
                Tarefa tarefa = this.tarefaModel.find(Integer.parseInt(id));
                this.tarefaUpdate = tarefa;
                this.jTextFieldTitulo.setText(tarefa.getTitulo());
                this.jComboBoxUsuario.setEditable(true);
                this.jComboBoxUsuario.setSelectedItem(new CustomCombo(tarefa.getUsuarioByIdUsuarioExecutor().getId(), tarefa.getUsuarioByIdUsuarioExecutor().getNome()));
                this.jComboBoxUsuario.setEditable(false);
                this.jComboBoxUsuario.setEnabled(false);
                this.jButtonCancelar.setVisible(true);
                this.jComboBoxEsforco.setSelectedIndex(tarefa.getEsforcoEstimado());
                this.jTextAreaDescricao.setText(tarefa.getDescricao());
                this.jPanel1.setBorder(BorderFactory.createTitledBorder("Edição de tarefa"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());

        }
    }//GEN-LAST:event_jTableTarefaMouseClicked

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        try {
            this.jTextFieldTitulo.setText(this.jTextFieldTitulo.getText().trim());
            if (this.jTextFieldTitulo.getText().equals("")) {
                JOptionPane.showMessageDialog(jPanel1, "Preencha um título");
            } else if( this.jComboBoxUsuario.getSelectedIndex()== 0){
                JOptionPane.showMessageDialog(jPanel1, "Selecione o responsável");
            } else if( this.jComboBoxEsforco.getSelectedIndex()== 0){
                JOptionPane.showMessageDialog(jPanel1, "Selecione o esforço");
            }else{
                Tarefa tarefa;
                if(this.tarefaUpdate == null){
                    tarefa = new Tarefa();
                    tarefa.setTitulo(this.jTextFieldTitulo.getText());
                    tarefa.setUsuarioByIdUsuarioCriador(this.framePrincipal.usuarioLogado);
                    CustomCombo ccu = (CustomCombo)this.jComboBoxUsuario.getSelectedItem();
                    tarefa.setUsuarioByIdUsuarioExecutor(new Usuario(ccu.getKey(),""));
                    CustomCombo cce = (CustomCombo)this.jComboBoxEsforco.getSelectedItem();
                    tarefa.setEsforcoEstimado(cce.getKey());
                    tarefa.setDescricao(this.jTextAreaDescricao.getText());
                    tarefa.setStatus(Tarefa.PARADA);
                    this.tarefaModel.create(tarefa);
                }else{
                    tarefa = this.tarefaUpdate;
                    tarefa.setTitulo(this.jTextFieldTitulo.getText());
                    CustomCombo cce = (CustomCombo)this.jComboBoxEsforco.getSelectedItem();
                    tarefa.setEsforcoEstimado(cce.getKey());
                    tarefa.setDescricao(this.jTextAreaDescricao.getText());
                    this.tarefaModel.update(tarefa);
                }
                preencheTabela();
                resetCadastro();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());

        }
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        resetCadastro();

    }//GEN-LAST:event_jButtonCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JComboBox jComboBoxEsforco;
    private javax.swing.JComboBox jComboBoxUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableTarefa;
    private javax.swing.JTextArea jTextAreaDescricao;
    private javax.swing.JTextField jTextFieldTitulo;
    // End of variables declaration//GEN-END:variables
}
